name: basicmvvm
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.5.0
  cupertino_icons: ^1.0.0
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  responsive_screen: ^1.0.0
  stacked: ^1.7.6
  stacked_services: ^0.5.4+4

dev_dependencies:
  auto_route_generator: ^0.5.0
  build_runner:
    ^1.10.0

    # flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_test:
    sdk: flutter
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
